/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterConfirmRouteImport } from './routes/register_.confirm'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppQrTicketRouteImport } from './routes/_app/qr-ticket'
import { Route as AppLegalAcceptanceRouteImport } from './routes/_app/legal-acceptance'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as NameTokenRouteImport } from './routes/$name.$token'
import { Route as AppTicketsIndexRouteImport } from './routes/_app/tickets/index'
import { Route as AppLocationsIndexRouteImport } from './routes/_app/locations/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppTicketsNewRouteImport } from './routes/_app/tickets/new'
import { Route as AppLocationsNewRouteImport } from './routes/_app/locations/new'
import { Route as AppEventsNewRouteImport } from './routes/_app/events/new'
import { Route as AppTicketsDocumentIdEditRouteImport } from './routes/_app/tickets/$documentId/edit'
import { Route as AppLocationsDocumentIdEditRouteImport } from './routes/_app/locations/$documentId/edit'
import { Route as AppEventsDocumentIdEditRouteImport } from './routes/_app/events/$documentId/edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterConfirmRoute = RegisterConfirmRouteImport.update({
  id: '/register_/confirm',
  path: '/register/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppQrTicketRoute = AppQrTicketRouteImport.update({
  id: '/qr-ticket',
  path: '/qr-ticket',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalAcceptanceRoute = AppLegalAcceptanceRouteImport.update({
  id: '/legal-acceptance',
  path: '/legal-acceptance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const NameTokenRoute = NameTokenRouteImport.update({
  id: '/$name/$token',
  path: '/$name/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIndexRoute = AppLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsNewRoute = AppTicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsNewRoute = AppLocationsNewRouteImport.update({
  id: '/locations/new',
  path: '/locations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsDocumentIdEditRoute =
  AppTicketsDocumentIdEditRouteImport.update({
    id: '/tickets/$documentId/edit',
    path: '/tickets/$documentId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppLocationsDocumentIdEditRoute =
  AppLocationsDocumentIdEditRouteImport.update({
    id: '/locations/$documentId/edit',
    path: '/locations/$documentId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppEventsDocumentIdEditRoute = AppEventsDocumentIdEditRouteImport.update({
  id: '/events/$documentId/edit',
  path: '/events/$documentId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$name/$token': typeof NameTokenRoute
  '/dashboard': typeof AppDashboardRoute
  '/legal-acceptance': typeof AppLegalAcceptanceRoute
  '/qr-ticket': typeof AppQrTicketRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/register/confirm': typeof RegisterConfirmRoute
  '/events/new': typeof AppEventsNewRoute
  '/locations/new': typeof AppLocationsNewRoute
  '/tickets/new': typeof AppTicketsNewRoute
  '/events/': typeof AppEventsIndexRoute
  '/locations/': typeof AppLocationsIndexRoute
  '/tickets/': typeof AppTicketsIndexRoute
  '/events/$documentId/edit': typeof AppEventsDocumentIdEditRoute
  '/locations/$documentId/edit': typeof AppLocationsDocumentIdEditRoute
  '/tickets/$documentId/edit': typeof AppTicketsDocumentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$name/$token': typeof NameTokenRoute
  '/dashboard': typeof AppDashboardRoute
  '/legal-acceptance': typeof AppLegalAcceptanceRoute
  '/qr-ticket': typeof AppQrTicketRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/register/confirm': typeof RegisterConfirmRoute
  '/events/new': typeof AppEventsNewRoute
  '/locations/new': typeof AppLocationsNewRoute
  '/tickets/new': typeof AppTicketsNewRoute
  '/events': typeof AppEventsIndexRoute
  '/locations': typeof AppLocationsIndexRoute
  '/tickets': typeof AppTicketsIndexRoute
  '/events/$documentId/edit': typeof AppEventsDocumentIdEditRoute
  '/locations/$documentId/edit': typeof AppLocationsDocumentIdEditRoute
  '/tickets/$documentId/edit': typeof AppTicketsDocumentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$name/$token': typeof NameTokenRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/legal-acceptance': typeof AppLegalAcceptanceRoute
  '/_app/qr-ticket': typeof AppQrTicketRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/register_/confirm': typeof RegisterConfirmRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/locations/new': typeof AppLocationsNewRoute
  '/_app/tickets/new': typeof AppTicketsNewRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/locations/': typeof AppLocationsIndexRoute
  '/_app/tickets/': typeof AppTicketsIndexRoute
  '/_app/events/$documentId/edit': typeof AppEventsDocumentIdEditRoute
  '/_app/locations/$documentId/edit': typeof AppLocationsDocumentIdEditRoute
  '/_app/tickets/$documentId/edit': typeof AppTicketsDocumentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/$name/$token'
    | '/dashboard'
    | '/legal-acceptance'
    | '/qr-ticket'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/auth/callback'
    | '/register/confirm'
    | '/events/new'
    | '/locations/new'
    | '/tickets/new'
    | '/events/'
    | '/locations/'
    | '/tickets/'
    | '/events/$documentId/edit'
    | '/locations/$documentId/edit'
    | '/tickets/$documentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/$name/$token'
    | '/dashboard'
    | '/legal-acceptance'
    | '/qr-ticket'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/auth/callback'
    | '/register/confirm'
    | '/events/new'
    | '/locations/new'
    | '/tickets/new'
    | '/events'
    | '/locations'
    | '/tickets'
    | '/events/$documentId/edit'
    | '/locations/$documentId/edit'
    | '/tickets/$documentId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/$name/$token'
    | '/_app/dashboard'
    | '/_app/legal-acceptance'
    | '/_app/qr-ticket'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/staff'
    | '/auth/callback'
    | '/register_/confirm'
    | '/_app/events/new'
    | '/_app/locations/new'
    | '/_app/tickets/new'
    | '/_app/events/'
    | '/_app/locations/'
    | '/_app/tickets/'
    | '/_app/events/$documentId/edit'
    | '/_app/locations/$documentId/edit'
    | '/_app/tickets/$documentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  NameTokenRoute: typeof NameTokenRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RegisterConfirmRoute: typeof RegisterConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register_/confirm': {
      id: '/register_/confirm'
      path: '/register/confirm'
      fullPath: '/register/confirm'
      preLoaderRoute: typeof RegisterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qr-ticket': {
      id: '/_app/qr-ticket'
      path: '/qr-ticket'
      fullPath: '/qr-ticket'
      preLoaderRoute: typeof AppQrTicketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal-acceptance': {
      id: '/_app/legal-acceptance'
      path: '/legal-acceptance'
      fullPath: '/legal-acceptance'
      preLoaderRoute: typeof AppLegalAcceptanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/$name/$token': {
      id: '/$name/$token'
      path: '/$name/$token'
      fullPath: '/$name/$token'
      preLoaderRoute: typeof NameTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tickets/': {
      id: '/_app/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations/': {
      id: '/_app/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AppLocationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/new': {
      id: '/_app/tickets/new'
      path: '/tickets/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof AppTicketsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations/new': {
      id: '/_app/locations/new'
      path: '/locations/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof AppLocationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/$documentId/edit': {
      id: '/_app/tickets/$documentId/edit'
      path: '/tickets/$documentId/edit'
      fullPath: '/tickets/$documentId/edit'
      preLoaderRoute: typeof AppTicketsDocumentIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations/$documentId/edit': {
      id: '/_app/locations/$documentId/edit'
      path: '/locations/$documentId/edit'
      fullPath: '/locations/$documentId/edit'
      preLoaderRoute: typeof AppLocationsDocumentIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$documentId/edit': {
      id: '/_app/events/$documentId/edit'
      path: '/events/$documentId/edit'
      fullPath: '/events/$documentId/edit'
      preLoaderRoute: typeof AppEventsDocumentIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppLegalAcceptanceRoute: typeof AppLegalAcceptanceRoute
  AppQrTicketRoute: typeof AppQrTicketRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppLocationsNewRoute: typeof AppLocationsNewRoute
  AppTicketsNewRoute: typeof AppTicketsNewRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppLocationsIndexRoute: typeof AppLocationsIndexRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
  AppEventsDocumentIdEditRoute: typeof AppEventsDocumentIdEditRoute
  AppLocationsDocumentIdEditRoute: typeof AppLocationsDocumentIdEditRoute
  AppTicketsDocumentIdEditRoute: typeof AppTicketsDocumentIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLegalAcceptanceRoute: AppLegalAcceptanceRoute,
  AppQrTicketRoute: AppQrTicketRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppEventsNewRoute: AppEventsNewRoute,
  AppLocationsNewRoute: AppLocationsNewRoute,
  AppTicketsNewRoute: AppTicketsNewRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppLocationsIndexRoute: AppLocationsIndexRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
  AppEventsDocumentIdEditRoute: AppEventsDocumentIdEditRoute,
  AppLocationsDocumentIdEditRoute: AppLocationsDocumentIdEditRoute,
  AppTicketsDocumentIdEditRoute: AppTicketsDocumentIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  NameTokenRoute: NameTokenRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RegisterConfirmRoute: RegisterConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
