import { vi } from 'vitest'

vi.mock('@repo/i18n/server', () => ({
  TranslationService: class TranslationService {},
}))

Object.assign(process.env, {
  NODE_ENV: 'test',
  PORT: '3000',
  JWT_SECRET: 'test-jwt-secret-do-not-use-in-production',
  REFRESH_TOKEN_SECRET: 'test-refresh-token-secret-do-not-use-in-production',
  API_PUBLIC_URL: 'http://localhost:3000',
  DASHBOARD_URL: 'http://localhost:3002',
  WEB_URL: 'http://localhost:3001',
  ADMIN_URL: 'http://localhost:3003',
  CORS_ALLOWED_ORIGINS: 'http://localhost:3001,http://localhost:3002,http://localhost:3003',
  TRUST_PROXY_HOPS: '0',
  RATE_LIMIT_PUBLIC_LIMIT: '120',
  RATE_LIMIT_PUBLIC_TTL_MS: '60000',
  RATE_LIMIT_AUTHENTICATED_LIMIT: '240',
  RATE_LIMIT_AUTHENTICATED_TTL_MS: '60000',
  RATE_LIMIT_LOGIN_LIMIT: '10',
  RATE_LIMIT_LOGIN_TTL_MS: '900000',
  RATE_LIMIT_AUTH_SENSITIVE_LIMIT: '5',
  RATE_LIMIT_AUTH_SENSITIVE_TTL_MS: '900000',
  RATE_LIMIT_AUTH_CONFIRM_LIMIT: '20',
  RATE_LIMIT_AUTH_CONFIRM_TTL_MS: '900000',
  RATE_LIMIT_REFRESH_LIMIT: '30',
  RATE_LIMIT_REFRESH_TTL_MS: '60000',
  RATE_LIMIT_PURCHASE_LIMIT: '10',
  RATE_LIMIT_PURCHASE_TTL_MS: '60000',
  RATE_LIMIT_QR_LIMIT: '20',
  RATE_LIMIT_QR_TTL_MS: '60000',
  RATE_LIMIT_CHECK_IN_LIMIT: '60',
  RATE_LIMIT_CHECK_IN_TTL_MS: '60000',
  RATE_LIMIT_GEO_LIMIT: '30',
  RATE_LIMIT_GEO_TTL_MS: '60000',
  DATABASE_URL: 'postgres://test:test@localhost:5432/test',
  DATABASE_MIGRATION_URL: 'postgres://test:test@localhost:5432/test',
  UPLOAD_MAX_BYTES: '10485760',
  IMAGE_MAX_DIMENSION: '2048',
  IMAGE_QUALITY: '82',
  R2_ACCOUNT_ID: 'test-r2-account',
  R2_ACCESS_KEY_ID: 'test-r2-access-key',
  R2_SECRET_ACCESS_KEY: 'test-r2-secret-key',
  R2_BUCKET: 'test-bucket',
  R2_PUBLIC_BASE_URL: 'http://localhost:3000/files',
  AWS_REGION: 'sa-east-1',
  AWS_ACCESS_KEY_ID: '',
  AWS_SECRET_ACCESS_KEY: '',
  MAIL_DOMAIN: 'example.test',
  MAIL_REPLY_TO: '',
  MAIL_SMOKE_TO: 'smoke@example.test',
  GOOGLE_CLIENT_ID: 'test-google-client-id',
  GOOGLE_CLIENT_SECRET: 'test-google-client-secret',
  MERCADOPAGO_ACCESS_TOKEN: 'test-mercado-pago-token',
  MERCADOPAGO_WEBHOOK_SECRET: 'test-mercado-pago-secret',
  MERCADOPAGO_TEST_MODE: 'false',
})
