export const INTERNAL_JOB_STEP = {
  EXPIRE_PURCHASE_RESERVATIONS: 'expire-purchase-reservations',
  CLEANUP_STALE_PENDING_ORDERS: 'cleanup-stale-pending-orders',
  CLEANUP_API_ERROR_RECORDS: 'cleanup-api-error-records',
  CLEANUP_USER_REGISTRATION_TOKENS: 'cleanup-user-registration-tokens',
  CLEANUP_OWNER_REGISTRATION_TOKENS: 'cleanup-owner-registration-tokens',
  CLEANUP_PASSWORD_RESET_TOKENS: 'cleanup-password-reset-tokens',
  CLEANUP_ACCOUNT_SESSIONS: 'cleanup-account-sessions',
  CLEANUP_STAFF_INVITATIONS: 'cleanup-staff-invitations',
} as const

export type InternalJobStepName = (typeof INTERNAL_JOB_STEP)[keyof typeof INTERNAL_JOB_STEP]

export const INTERNAL_JOB_STEP_ORDER = [
  INTERNAL_JOB_STEP.EXPIRE_PURCHASE_RESERVATIONS,
  INTERNAL_JOB_STEP.CLEANUP_STALE_PENDING_ORDERS,
  INTERNAL_JOB_STEP.CLEANUP_API_ERROR_RECORDS,
  INTERNAL_JOB_STEP.CLEANUP_USER_REGISTRATION_TOKENS,
  INTERNAL_JOB_STEP.CLEANUP_OWNER_REGISTRATION_TOKENS,
  INTERNAL_JOB_STEP.CLEANUP_PASSWORD_RESET_TOKENS,
  INTERNAL_JOB_STEP.CLEANUP_ACCOUNT_SESSIONS,
  INTERNAL_JOB_STEP.CLEANUP_STAFF_INVITATIONS,
] as const satisfies readonly InternalJobStepName[]
