/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterConfirmRouteImport } from './routes/register_.confirm'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as PublicEventsRouteImport } from './routes/_public/events'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppLegalAcceptanceRouteImport } from './routes/_app/legal-acceptance'
import { Route as PublicEventsIndexRouteImport } from './routes/_public/events.index'
import { Route as CheckoutOrderIdSuccessRouteImport } from './routes/checkout.$orderId.success'
import { Route as CheckoutOrderIdPendingRouteImport } from './routes/checkout.$orderId.pending'
import { Route as CheckoutOrderIdErrorRouteImport } from './routes/checkout.$orderId.error'
import { Route as PublicOrganizationsSlugRouteImport } from './routes/_public/organizations.$slug'
import { Route as PublicEventsSlugRouteImport } from './routes/_public/events.$slug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterConfirmRoute = RegisterConfirmRouteImport.update({
  id: '/register_/confirm',
  path: '/register/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalAcceptanceRoute = AppLegalAcceptanceRouteImport.update({
  id: '/legal-acceptance',
  path: '/legal-acceptance',
  getParentRoute: () => AppRoute,
} as any)
const PublicEventsIndexRoute = PublicEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicEventsRoute,
} as any)
const CheckoutOrderIdSuccessRoute = CheckoutOrderIdSuccessRouteImport.update({
  id: '/checkout/$orderId/success',
  path: '/checkout/$orderId/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdPendingRoute = CheckoutOrderIdPendingRouteImport.update({
  id: '/checkout/$orderId/pending',
  path: '/checkout/$orderId/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdErrorRoute = CheckoutOrderIdErrorRouteImport.update({
  id: '/checkout/$orderId/error',
  path: '/checkout/$orderId/error',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicOrganizationsSlugRoute = PublicOrganizationsSlugRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsSlugRoute = PublicEventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/legal-acceptance': typeof AppLegalAcceptanceRoute
  '/orders': typeof AppOrdersRoute
  '/settings': typeof AppSettingsRoute
  '/tickets': typeof AppTicketsRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/register/confirm': typeof RegisterConfirmRoute
  '/events/$slug': typeof PublicEventsSlugRoute
  '/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/checkout/$orderId/error': typeof CheckoutOrderIdErrorRoute
  '/checkout/$orderId/pending': typeof CheckoutOrderIdPendingRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/events/': typeof PublicEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/legal-acceptance': typeof AppLegalAcceptanceRoute
  '/orders': typeof AppOrdersRoute
  '/settings': typeof AppSettingsRoute
  '/tickets': typeof AppTicketsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/register/confirm': typeof RegisterConfirmRoute
  '/events/$slug': typeof PublicEventsSlugRoute
  '/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/checkout/$orderId/error': typeof CheckoutOrderIdErrorRoute
  '/checkout/$orderId/pending': typeof CheckoutOrderIdPendingRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/events': typeof PublicEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/legal-acceptance': typeof AppLegalAcceptanceRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/_public/events': typeof PublicEventsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/register_/confirm': typeof RegisterConfirmRoute
  '/_public/events/$slug': typeof PublicEventsSlugRoute
  '/_public/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/checkout/$orderId/error': typeof CheckoutOrderIdErrorRoute
  '/checkout/$orderId/pending': typeof CheckoutOrderIdPendingRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/_public/events/': typeof PublicEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/legal-acceptance'
    | '/orders'
    | '/settings'
    | '/tickets'
    | '/events'
    | '/auth/callback'
    | '/register/confirm'
    | '/events/$slug'
    | '/organizations/$slug'
    | '/checkout/$orderId/error'
    | '/checkout/$orderId/pending'
    | '/checkout/$orderId/success'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/legal-acceptance'
    | '/orders'
    | '/settings'
    | '/tickets'
    | '/auth/callback'
    | '/register/confirm'
    | '/events/$slug'
    | '/organizations/$slug'
    | '/checkout/$orderId/error'
    | '/checkout/$orderId/pending'
    | '/checkout/$orderId/success'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_public'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/legal-acceptance'
    | '/_app/orders'
    | '/_app/settings'
    | '/_app/tickets'
    | '/_public/events'
    | '/auth/callback'
    | '/register_/confirm'
    | '/_public/events/$slug'
    | '/_public/organizations/$slug'
    | '/checkout/$orderId/error'
    | '/checkout/$orderId/pending'
    | '/checkout/$orderId/success'
    | '/_public/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RegisterConfirmRoute: typeof RegisterConfirmRoute
  CheckoutOrderIdErrorRoute: typeof CheckoutOrderIdErrorRoute
  CheckoutOrderIdPendingRoute: typeof CheckoutOrderIdPendingRoute
  CheckoutOrderIdSuccessRoute: typeof CheckoutOrderIdSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register_/confirm': {
      id: '/register_/confirm'
      path: '/register/confirm'
      fullPath: '/register/confirm'
      preLoaderRoute: typeof RegisterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal-acceptance': {
      id: '/_app/legal-acceptance'
      path: '/legal-acceptance'
      fullPath: '/legal-acceptance'
      preLoaderRoute: typeof AppLegalAcceptanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/events/': {
      id: '/_public/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof PublicEventsIndexRouteImport
      parentRoute: typeof PublicEventsRoute
    }
    '/checkout/$orderId/success': {
      id: '/checkout/$orderId/success'
      path: '/checkout/$orderId/success'
      fullPath: '/checkout/$orderId/success'
      preLoaderRoute: typeof CheckoutOrderIdSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId/pending': {
      id: '/checkout/$orderId/pending'
      path: '/checkout/$orderId/pending'
      fullPath: '/checkout/$orderId/pending'
      preLoaderRoute: typeof CheckoutOrderIdPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId/error': {
      id: '/checkout/$orderId/error'
      path: '/checkout/$orderId/error'
      fullPath: '/checkout/$orderId/error'
      preLoaderRoute: typeof CheckoutOrderIdErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/organizations/$slug': {
      id: '/_public/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof PublicOrganizationsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events/$slug': {
      id: '/_public/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof PublicEventsSlugRouteImport
      parentRoute: typeof PublicEventsRoute
    }
  }
}

interface AppRouteChildren {
  AppLegalAcceptanceRoute: typeof AppLegalAcceptanceRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTicketsRoute: typeof AppTicketsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLegalAcceptanceRoute: AppLegalAcceptanceRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTicketsRoute: AppTicketsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicEventsRouteChildren {
  PublicEventsSlugRoute: typeof PublicEventsSlugRoute
  PublicEventsIndexRoute: typeof PublicEventsIndexRoute
}

const PublicEventsRouteChildren: PublicEventsRouteChildren = {
  PublicEventsSlugRoute: PublicEventsSlugRoute,
  PublicEventsIndexRoute: PublicEventsIndexRoute,
}

const PublicEventsRouteWithChildren = PublicEventsRoute._addFileChildren(
  PublicEventsRouteChildren,
)

interface PublicRouteChildren {
  PublicEventsRoute: typeof PublicEventsRouteWithChildren
  PublicOrganizationsSlugRoute: typeof PublicOrganizationsSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicEventsRoute: PublicEventsRouteWithChildren,
  PublicOrganizationsSlugRoute: PublicOrganizationsSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RegisterConfirmRoute: RegisterConfirmRoute,
  CheckoutOrderIdErrorRoute: CheckoutOrderIdErrorRoute,
  CheckoutOrderIdPendingRoute: CheckoutOrderIdPendingRoute,
  CheckoutOrderIdSuccessRoute: CheckoutOrderIdSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
