export const MERCADO_PAGO_CHECKOUT_PRO_PORT = Symbol('MERCADO_PAGO_CHECKOUT_PRO_PORT')
export const MERCADO_PAGO_OAUTH_PORT = Symbol('MERCADO_PAGO_OAUTH_PORT')
export const MERCADO_PAGO_CREDENTIAL_RESOLVER = Symbol('MERCADO_PAGO_CREDENTIAL_RESOLVER')
